--Task 4
--Q1. Write an SQL query to find out which customers have not placed any orders.
select customerID, firstname,phone from customers
where CustomerID not in (select CustomerID from Orders)

--Q2. Write an SQL query to find the total number of products available for sale.
select * from inventory
select sum(QuantityInStock) as TotalProducts from inventory

--Q3.Write an SQL query to calculate the total revenue generated by TechShop.
select sum(od.quantity * p.price) from OrderDetails od
join Products p on p.ProductID=od.ProductID;

--Q4.Write an SQL query to calculate the average quantity ordered for products in a specific category. Allow users to input the category name as a parameter.
select Avg(Quantity) AvgQuantity from OrderDetails 
where ProductID in (select ProductID from Products  where category = 'computing devices');

--Q5.Write an SQL query to calculate the total revenue generated by a specific customer.
--Allow users to input the customer ID as a parameter.
select o.CustomerID as customerID,sum(od.quantity * p.price) as TotalRevenue from orders o
join OrderDetails od on o.OrderID = od.OrderID
join Products p on p.ProductID = od.ProductID
where o.CustomerID in (select CustomerID from Orders where customerID = 5)
group by o.customerID;

--Q6.Write an SQL query to find the customers who have placed the most orders. 
--List their names and the number of orders they've placed.
select c.CustomerID, c.FirstName, c.LastName, count(o.OrderID) as OrderCount
from Customers c
join Orders o on c.CustomerID = o.CustomerID
group by c.CustomerID, c.FirstName, c.LastName
order by OrderCount desc;

-- Q7.Write an SQL query to find the most popular product category, 
--which is the one with the highest total quantity ordered across all orders.
select  p.category , sum(od.quantity) TotalQuantity from OrderDetails od
join Products p on p.ProductID = od.ProductID
group by p.category
order by TotalQuantity desc;

select top 1 p.category , sum(od.quantity) TotalQuantity from OrderDetails od
join Products p on p.ProductID = od.ProductID
group by p.category
order by TotalQuantity desc;

--Q8.Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. 
--List their name and total spending.
select c.FirstName,c.LastName ,o.TotalAmount from Customers c
join orders o on o.CustomerID = c.CustomerID
where o.TotalAmount = (select max(totalamount) from orders);

--9. Write an SQL query to calculate the average order value 
--(total revenue divided by the number of orders) for all customers.
select sum(totalamount) / count(orderID) as AVgOrderValue from orders;

--10. Write an SQL query to find the total number of orders placed by each customer 
--and list their names along with the order count.
select c.CustomerID,c.firstname,count(orderId) ordercount from Customers c
left join Orders o on o.CustomerID=c.CustomerID
group by c.CustomerID,c.FirstName
order by ordercount desc;
