--Task 4
--Q1. Write an SQL query to find out which customers have not placed any orders.
select customerID, firstname,phone from customers
where CustomerID not in (select CustomerID from Orders)

--Q2. Write an SQL query to find the total number of products available for sale.
select * from inventory
select sum(QuantityInStock) as TotalProducts from inventory

--Q3.Write an SQL query to calculate the total revenue generated by TechShop.
select sum(od.quantity * p.price) from OrderDetails od
join Products p on p.ProductID=od.ProductID;

--Q4.Write an SQL query to calculate the average quantity ordered for products in a specific category. Allow users to input the category name as a parameter.
select Avg(Quantity) AvgQuantity from OrderDetails 
where ProductID in (select ProductID from Products  where category = 'computing devices');
