--Task 3
--Q1 .Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order.
select o.* , c.firstname ,c.lastname,c.email from orders o
left join Customers c on c.CustomerID = o.CustomerID;

--Q2. Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue.
select p.productname as ProductName, sum (od.quantity * p.price) as TotalRevenue from OrderDetails od
join Products p on p.ProductID = od.ProductID
group by productname;

--Q3.Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information.
select c.firstname , c.email , c.phone from Customers c
join Orders o  on o.CustomerID=c.CustomerID

-- Q4. Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered.
select top 1 p.ProductName , sum(od.Quantity) as totalQuanity from OrderDetails od
join Products p on p.ProductID = od.ProductID
group by p.ProductName
order by totalQuanity desc;

--Q5.Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
select ProductName , category from Products
order by category;

--Q6 .Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value.
select c.firstname , c.lastname , avg(o.totalamount) as AvgOrderValue from Customers c
join Orders o on o.CustomerID=c.CustomerID
group by c.FirstName,c.LastName;

--Q7 .Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue.
select Top 1 o.orderid , c.firstname , c.lastname , c.email ,c.phone,o.totalamount from Orders o
join Customers c on c.CustomerID=o.CustomerID
order by o.TotalAmount desc;

--Q8.Write an SQL query to list electronic gadgets and the number of times each product has been ordered.
select p.productname , count(od.quantity)TotalQuantity from OrderDetails od
join Products p on p.ProductID=od.ProductID
group by ProductName

--Q9. Write an SQL query to find customers who have purchased a specific electronic gadget product. Allow users to input the product name as a parameter.
select firstname as Customername from Customers c
join Orders o on o.CustomerID = c.CustomerID
join OrderDetails od on od.OrderID = o.OrderID
join Products p on p.ProductID = od.ProductID
where p.ProductName = 'Laptop';

--Q10. Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. 
--Allow users to input the start and end dates as parameters.
select sum(totalamount) as TotalRevenue from orders
where OrderDate between '2025-01-01' and '2025-12-31';